# Docker Compose 파일 - Cafe24 서버 배포용

services:
  frontend:
    image: football-club-frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - football-club-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: football-club-backend:latest
    container_name: backend
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /opt/football-club/logs:/var/log/football-club
      - /opt/football-club/uploads:/opt/football-club/uploads
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - football-club-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /opt/football-club/mysql-data:/var/lib/mysql
      - /opt/football-club/mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    networks:
      - football-club-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    profiles:
      - with-db

networks:
  football-club-network:
    driver: bridge

secrets:
  mysql_root_password:
    file: /opt/football-club/secrets/mysql_root_password.txt
  mysql_password:
    file: /opt/football-club/secrets/mysql_password.txt
