version: '3.8'

services:
  frontend:
    image: football-club-frontend:latest
    container_name: football-club-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - football-network

networks:
  football-network:
    driver: bridge
