spring:
  application:
    name: BE

  # 데이터베이스 설정 (H2 - 개발용)
  datasource:
    url: jdbc:h2:mem:footballclub
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # H2 콘솔 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # 파일 업로드 설정 (선수 사진용)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api

# 서브도메인 설정
app:
  subdomain:
    enabled: true
    pattern: "{team}.footballclub.com"
  admin:
    subdomain: admin.footballclub.com
  upload:
    path: /uploads/players

# 로깅 설정
#logging:
#  level:
#    io.be: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
