spring:
  application:
    name: BE

  # 활성 프로필 설정 (기본값: local)
  profiles:
    active: prod

  # 파일 업로드 설정 (선수 사진용)
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# 서버 설정
server:
  port: 8082
  servlet:
    context-path: /api

# 서브도메인 설정
app:
  subdomain:
    enabled: true
    pattern: "{team}.footballclub.com"
  admin:
    subdomain: admin.footballclub.com
  upload:
    path: /uploads/players

# 공통 로깅 설정
logging:
  level:
    io.be.aspect.ApiLoggingAspect: INFO
    io.be.exception.GlobalExceptionHandler: ERROR
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
