name: Backend Deploy to EC2

on:
  push:
    branches: [ main ]
    # paths: ['be/**']  # 임시로 경로 조건 제거
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Create application-prod.yml with secrets
      run: echo "${{ secrets.APPLICATION_PROD_YML }}" > be/src/main/resources/application-prod.yml
      
    - name: Build Backend Docker image
      run: |
        docker build -f be/Dockerfile -t football-club-backend:latest ./be
        docker save football-club-backend:latest | gzip > football-club-backend.tar.gz
        
    - name: Copy Backend image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "football-club-backend.tar.gz,docker/be-compose.yml,scripts/be-deploy.sh"
        target: "/home/${{ secrets.EC2_USERNAME }}/football-club-backend"
        
    - name: Deploy Backend with Docker on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.EC2_USERNAME }}/football-club-backend
          chmod +x scripts/be-deploy.sh
          ./scripts/be-deploy.sh