# DEPRECATED: This workflow is no longer used
# Use cafe24-deploy-backend.yml and cafe24-deploy-frontend.yml instead

name: "[DEPRECATED] Deploy to Cafe24 Server"

on:
  # Disabled - use separate backend/frontend workflows instead
  # push:
  #   branches: [ asdasd ]
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Create application-prod.yml with secrets
      run: echo "${{ secrets.APPLICATION_PROD_YML }}" > be/src/main/resources/application-prod.yml

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./be
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/football-club-backend:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/football-club-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./fe
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/football-club-frontend:${{ github.sha }},${{ secrets.DOCKER_USERNAME }}/football-club-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CAFE24_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        ssh-keyscan -H ${{ secrets.CAFE24_HOST }} >> ~/.ssh/known_hosts

    - name: Copy docker-compose.yml to server
      run: |
        scp -i ~/.ssh/id_rsa docker-compose.yml root@${{ secrets.CAFE24_HOST }}:/opt/football-club/

    - name: Deploy on server
      run: |
        ssh -i ~/.ssh/id_rsa root@${{ secrets.CAFE24_HOST }} "
          cd /opt/football-club &&
          echo 'MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}' > .env &&
          echo 'MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}' >> .env &&
          echo 'MYSQL_USER=${{ secrets.MYSQL_USER }}' >> .env &&
          echo 'MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}' >> .env &&
          echo 'MYSQL_HOST=db' >> .env &&
          docker pull ${{ secrets.DOCKER_USERNAME }}/football-club-backend:${{ github.sha }} &&
          docker pull ${{ secrets.DOCKER_USERNAME }}/football-club-frontend:${{ github.sha }} &&
          docker tag ${{ secrets.DOCKER_USERNAME }}/football-club-backend:${{ github.sha }} football-club-backend:latest &&
          docker tag ${{ secrets.DOCKER_USERNAME }}/football-club-frontend:${{ github.sha }} football-club-frontend:latest &&
          docker-compose --profile with-db down --remove-orphans || true &&
          docker-compose --profile with-db up -d
        "

    - name: Deployment notification
      run: echo "✅ Deployment completed successfully!"
